<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Country Codes for Phone Numbers
    |--------------------------------------------------------------------------
    |
    | This is a list of country codes with their flags and names for use in forms
    | and displays throughout the application.
    |
    */
    'country_codes' => [
        '+93' => '🇦🇫 +93 (Afghanistan)',
        '+355' => '🇦🇱 +355 (Albania)',
        '+213' => '🇩🇿 +213 (Algeria)',
        '+1684' => '🇦🇸 +1684 (American Samoa)',
        '+376' => '🇦🇩 +376 (Andorra)',
        '+244' => '🇦🇴 +244 (Angola)',
        '+1264' => '🇦🇮 +1264 (Anguilla)',
        '+672' => '🇦🇶 +672 (Antarctica)',
        '+1268' => '🇦🇬 +1268 (Antigua and Barbuda)',
        '+54' => '🇦🇷 +54 (Argentina)',
        '+374' => '🇦🇲 +374 (Armenia)',
        '+297' => '🇦🇼 +297 (Aruba)',
        '+61' => '🇦🇺 +61 (Australia)',
        '+43' => '🇦🇹 +43 (Austria)',
        '+994' => '🇦🇿 +994 (Azerbaijan)',
        '+1242' => '🇧🇸 +1242 (Bahamas)',
        '+973' => '🇧🇭 +973 (Bahrain)',
        '+880' => '🇧🇩 +880 (Bangladesh)',
        '+1246' => '🇧🇧 +1246 (Barbados)',
        '+375' => '🇧🇾 +375 (Belarus)',
        '+32' => '🇧🇪 +32 (Belgium)',
        '+501' => '🇧🇿 +501 (Belize)',
        '+229' => '🇧🇯 +229 (Benin)',
        '+1441' => '🇧🇲 +1441 (Bermuda)',
        '+975' => '🇧🇹 +975 (Bhutan)',
        '+591' => '🇧🇴 +591 (Bolivia)',
        '+387' => '🇧🇦 +387 (Bosnia and Herzegovina)',
        '+267' => '🇧🇼 +267 (Botswana)',
        '+55' => '🇧🇷 +55 (Brazil)',
        '+246' => '🇮🇴 +246 (British Indian Ocean Territory)',
        '+1284' => '🇻🇬 +1284 (British Virgin Islands)',
        '+673' => '🇧🇳 +673 (Brunei)',
        '+359' => '🇧🇬 +359 (Bulgaria)',
        '+226' => '🇧🇫 +226 (Burkina Faso)',
        '+257' => '🇧🇮 +257 (Burundi)',
        '+855' => '🇰🇭 +855 (Cambodia)',
        '+237' => '🇨🇲 +237 (Cameroon)',
        '+1' => '🇨🇦 +1 (Canada)',
        '+238' => '🇨🇻 +238 (Cape Verde)',
        '+1345' => '🇰🇾 +1345 (Cayman Islands)',
        '+236' => '🇨🇫 +236 (Central African Republic)',
        '+235' => '🇹🇩 +235 (Chad)',
        '+56' => '🇨🇱 +56 (Chile)',
        '+86' => '🇨🇳 +86 (China)',
        '+61' => '🇨🇽 +61 (Christmas Island)',
        '+61' => '🇨🇨 +61 (Cocos Islands)',
        '+57' => '🇨🇴 +57 (Colombia)',
        '+269' => '🇰🇲 +269 (Comoros)',
        '+682' => '🇨🇰 +682 (Cook Islands)',
        '+506' => '🇨🇷 +506 (Costa Rica)',
        '+385' => '🇭🇷 +385 (Croatia)',
        '+53' => '🇨🇺 +53 (Cuba)',
        '+599' => '🇨🇼 +599 (Curacao)',
        '+357' => '🇨🇾 +357 (Cyprus)',
        '+420' => '🇨🇿 +420 (Czech Republic)',
        '+243' => '🇨🇩 +243 (Democratic Republic of the Congo)',
        '+45' => '🇩🇰 +45 (Denmark)',
        '+253' => '🇩🇯 +253 (Djibouti)',
        '+1767' => '🇩🇲 +1767 (Dominica)',
        '+1809' => '🇩🇴 +1809 (Dominican Republic)', // and +1829, +1849
        '+670' => '🇹🇱 +670 (East Timor)',
        '+593' => '🇪🇨 +593 (Ecuador)',
        '+20' => '🇪🇬 +20 (Egypt)',
        '+503' => '🇸🇻 +503 (El Salvador)',
        '+240' => '🇬🇶 +240 (Equatorial Guinea)',
        '+291' => '🇪🇷 +291 (Eritrea)',
        '+372' => '🇪🇪 +372 (Estonia)',
        '+268' => '🇸🇿 +268 (Eswatini)',
        '+251' => '🇪🇹 +251 (Ethiopia)',
        '+500' => '🇫🇰 +500 (Falkland Islands)',
        '+298' => '🇫🇴 +298 (Faroe Islands)',
        '+679' => '🇫🇯 +679 (Fiji)',
        '+358' => '🇫🇮 +358 (Finland)',
        '+33' => '🇫🇷 +33 (France)',
        '+689' => '🇵🇫 +689 (French Polynesia)',
        '+241' => '🇬🇦 +241 (Gabon)',
        '+220' => '🇬🇲 +220 (Gambia)',
        '+995' => '🇬🇪 +995 (Georgia)',
        '+49' => '🇩🇪 +49 (Germany)',
        '+233' => '🇬🇭 +233 (Ghana)',
        '+350' => '🇬🇮 +350 (Gibraltar)',
        '+30' => '🇬🇷 +30 (Greece)',
        '+299' => '🇬🇱 +299 (Greenland)',
        '+1473' => '🇬🇩 +1473 (Grenada)',
        '+1671' => '🇬🇺 +1671 (Guam)',
        '+502' => '🇬🇹 +502 (Guatemala)',
        '+44' => '🇬🇬 +44 (Guernsey)', // Guernsey, Jersey, Isle of Man share +44
        '+224' => '🇬🇳 +224 (Guinea)',
        '+245' => '🇬🇼 +245 (Guinea-Bissau)',
        '+592' => '🇬🇾 +592 (Guyana)',
        '+509' => '🇭🇹 +509 (Haiti)',
        '+504' => '🇭🇳 +504 (Honduras)',
        '+852' => '🇭🇰 +852 (Hong Kong)',
        '+36' => '🇭🇺 +36 (Hungary)',
        '+354' => '🇮🇸 +354 (Iceland)',
        '+91' => '🇮🇳 +91 (India)',
        '+62' => '🇮🇩 +62 (Indonesia)',
        '+98' => '🇮🇷 +98 (Iran)',
        '+964' => '🇮🇶 +964 (Iraq)',
        '+353' => '🇮🇪 +353 (Ireland)',
        '+44' => '🇮🇲 +44 (Isle of Man)',
        '+39' => '🇮🇹 +39 (Italy)',
        '+225' => '🇨🇮 +225 (Ivory Coast)',
        '+1876' => '🇯🇲 +1876 (Jamaica)',
        '+81' => '🇯🇵 +81 (Japan)',
        '+44' => '🇯🇪 +44 (Jersey)',
        '+962' => '🇯🇴 +962 (Jordan)',
        '+7' => '🇰🇿 +7 (Kazakhstan)', // Shares +7 with Russia
        '+254' => '🇰🇪 +254 (Kenya)',
        '+686' => '🇰🇮 +686 (Kiribati)',
        '+383' => '🇽🇰 +383 (Kosovo)',
        '+965' => '🇰🇼 +965 (Kuwait)',
        '+996' => '🇰🇬 +996 (Kyrgyzstan)',
        '+856' => '🇱🇦 +856 (Laos)',
        '+371' => '🇱🇻 +371 (Latvia)',
        '+961' => '🇱🇧 +961 (Lebanon)',
        '+266' => '🇱🇸 +266 (Lesotho)',
        '+231' => '🇱🇷 +231 (Liberia)',
        '+218' => '🇱🇾 +218 (Libya)',
        '+423' => '🇱🇮 +423 (Liechtenstein)',
        '+370' => '🇱🇹 +370 (Lithuania)',
        '+352' => '🇱🇺 +352 (Luxembourg)',
        '+853' => '🇲🇴 +853 (Macau)',
        '+261' => '🇲🇬 +261 (Madagascar)',
        '+265' => '🇲🇼 +265 (Malawi)',
        '+60' => '🇲🇾 +60 (Malaysia)',
        '+960' => '🇲🇻 +960 (Maldives)',
        '+223' => '🇲🇱 +223 (Mali)',
        '+356' => '🇲🇹 +356 (Malta)',
        '+692' => '🇲🇭 +692 (Marshall Islands)',
        '+222' => '🇲🇷 +222 (Mauritania)',
        '+230' => '🇲🇺 +230 (Mauritius)',
        '+262' => '🇾🇹 +262 (Mayotte)', // French overseas department
        '+52' => '🇲🇽 +52 (Mexico)',
        '+691' => '🇫🇲 +691 (Micronesia)',
        '+373' => '🇲🇩 +373 (Moldova)',
        '+377' => '🇲🇨 +377 (Monaco)',
        '+976' => '🇲🇳 +976 (Mongolia)',
        '+382' => '🇲🇪 +382 (Montenegro)',
        '+1664' => '🇲🇸 +1664 (Montserrat)',
        '+212' => '🇲🇦 +212 (Morocco)',
        '+258' => '🇲🇿 +258 (Mozambique)',
        '+95' => '🇲🇲 +95 (Myanmar)',
        '+264' => '🇳🇦 +264 (Namibia)',
        '+674' => '🇳🇷 +674 (Nauru)',
        '+977' => '🇳🇵 +977 (Nepal)',
        '+31' => '🇳🇱 +31 (Netherlands)',
        '+599' => '🇦🇳 +599 (Netherlands Antilles)', // Dissolved, split into Curacao and Sint Maarten etc.
        '+687' => '🇳🇨 +687 (New Caledonia)',
        '+64' => '🇳🇿 +64 (New Zealand)',
        '+505' => '🇳🇮 +505 (Nicaragua)',
        '+227' => '🇳🇪 +227 (Niger)',
        '+234' => '🇳🇬 +234 (Nigeria)',
        '+683' => '🇳🇺 +683 (Niue)',
        '+850' => '🇰🇵 +850 (North Korea)',
        '+389' => '🇲🇰 +389 (North Macedonia)',
        '+1670' => '🇲🇵 +1670 (Northern Mariana Islands)',
        '+47' => '🇳🇴 +47 (Norway)',
        '+968' => '🇴🇲 +968 (Oman)',
        '+92' => '🇵🇰 +92 (Pakistan)',
        '+680' => '🇵🇼 +680 (Palau)',
        '+970' => '🇵🇸 +970 (Palestine)',
        '+507' => '🇵🇦 +507 (Panama)',
        '+675' => '🇵🇬 +675 (Papua New Guinea)',
        '+595' => '🇵🇾 +595 (Paraguay)',
        '+51' => '🇵🇪 +51 (Peru)',
        '+63' => '🇵🇭 +63 (Philippines)',
        '+64' => '🇵🇳 +64 (Pitcairn Islands)', // Uses New Zealand code
        '+48' => '🇵🇱 +48 (Poland)',
        '+351' => '🇵🇹 +351 (Portugal)',
        '+1787' => '🇵🇷 +1787 (Puerto Rico)', // and +1939
        '+974' => '🇶🇦 +974 (Qatar)',
        '+242' => '🇨🇬 +242 (Republic of the Congo)',
        '+262' => '🇷🇪 +262 (Reunion)', // French overseas department
        '+40' => '🇷🇴 +40 (Romania)',
        '+7' => '🇷🇺 +7 (Russia)',
        '+250' => '🇷🇼 +250 (Rwanda)',
        '+590' => '🇧🇱 +590 (Saint Barthelemy)',
        '+290' => '🇸🇭 +290 (Saint Helena)',
        '+1869' => '🇰🇳 +1869 (Saint Kitts and Nevis)',
        '+1758' => '🇱🇨 +1758 (Saint Lucia)',
        '+590' => '🇲🇫 +590 (Saint Martin)',
        '+508' => '🇵🇲 +508 (Saint Pierre and Miquelon)',
        '+1784' => '🇻🇨 +1784 (Saint Vincent and the Grenadines)',
        '+685' => '🇼🇸 +685 (Samoa)',
        '+378' => '🇸🇲 +378 (San Marino)',
        '+239' => '🇸🇹 +239 (Sao Tome and Principe)',
        '+966' => '🇸🇦 +966 (Saudi Arabia)',
        '+221' => '🇸🇳 +221 (Senegal)',
        '+381' => '🇷🇸 +381 (Serbia)',
        '+248' => '🇸🇨 +248 (Seychelles)',
        '+232' => '🇸🇱 +232 (Sierra Leone)',
        '+65' => '🇸🇬 +65 (Singapore)',
        '+1721' => '🇸🇽 +1721 (Sint Maarten)',
        '+421' => '🇸🇰 +421 (Slovakia)',
        '+386' => '🇸🇮 +386 (Slovenia)',
        '+677' => '🇸🇧 +677 (Solomon Islands)',
        '+252' => '🇸🇴 +252 (Somalia)',
        '+27' => '🇿🇦 +27 (South Africa)',
        '+82' => '🇰🇷 +82 (South Korea)',
        '+211' => '🇸🇸 +211 (South Sudan)',
        '+34' => '🇪🇸 +34 (Spain)',
        '+94' => '🇱🇰 +94 (Sri Lanka)',
        '+249' => '🇸🇩 +249 (Sudan)',
        '+597' => '🇸🇷 +597 (Suriname)',
        '+47' => '🇸🇯 +47 (Svalbard and Jan Mayen)', // Norwegian territory
        '+46' => '🇸🇪 +46 (Sweden)',
        '+41' => '🇨🇭 +41 (Switzerland)',
        '+963' => '🇸🇾 +963 (Syria)',
        '+886' => '🇹🇼 +886 (Taiwan)',
        '+992' => '🇹🇯 +992 (Tajikistan)',
        '+255' => '🇹🇿 +255 (Tanzania)',
        '+66' => '🇹🇭 +66 (Thailand)',
        '+228' => '🇹🇬 +228 (Togo)',
        '+690' => '🇹🇰 +690 (Tokelau)',
        '+676' => '🇹🇴 +676 (Tonga)',
        '+1868' => '🇹🇹 +1868 (Trinidad and Tobago)',
        '+216' => '🇹🇳 +216 (Tunisia)',
        '+90' => '🇹🇷 +90 (Turkey)',
        '+993' => '🇹🇲 +993 (Turkmenistan)',
        '+1649' => '🇹🇨 +1649 (Turks and Caicos Islands)',
        '+688' => '🇹🇻 +688 (Tuvalu)',
        '+1340' => '🇻🇮 +1340 (U.S. Virgin Islands)',
        '+256' => '🇺🇬 +256 (Uganda)',
        '+380' => '🇺🇦 +380 (Ukraine)',
        '+971' => '🇦🇪 +971 (United Arab Emirates)',
        '+44' => '🇬🇧 +44 (United Kingdom)',
        '+1' => '🇺🇸 +1 (United States)',
        '+598' => '🇺🇾 +598 (Uruguay)',
        '+998' => '🇺🇿 +998 (Uzbekistan)',
        '+678' => '🇻🇺 +678 (Vanuatu)',
        '+379' => '🇻🇦 +379 (Vatican City)',
        '+58' => '🇻🇪 +58 (Venezuela)',
        '+84' => '🇻🇳 +84 (Vietnam)',
        '+681' => '🇼🇫 +681 (Wallis and Futuna)',
        '+212' => '🇪🇭 +212 (Western Sahara)', // Disputed, Morocco administers
        '+967' => '🇾🇪 +967 (Yemen)',
        '+260' => '🇿🇲 +260 (Zambia)',
        '+263' => '🇿🇼 +263 (Zimbabwe)',
    ],

    /*
    |--------------------------------------------------------------------------
    | Nationalities
    |--------------------------------------------------------------------------
    |
    | This list maps country names to their common demonyms (nationalities).
    |
    */
    'nationalities' => [
        'Afghan' => 'Afghan',
        'Albanian' => 'Albanian',
        'Algerian' => 'Algerian',
        'American Samoan' => 'American Samoan',
        'Andorran' => 'Andorran',
        'Angolan' => 'Angolan',
        'Anguillan' => 'Anguillan',
        'Antarctic' => 'Antarctic',
        'Antiguan or Barbudan' => 'Antiguan or Barbudan',
        'Argentine' => 'Argentine',
        'Armenian' => 'Armenian',
        'Aruban' => 'Aruban',
        'Australian' => 'Australian',
        'Austrian' => 'Austrian',
        'Azerbaijani' => 'Azerbaijani',
        'Bahamian' => 'Bahamian',
        'Bahraini' => 'Bahraini',
        'Bangladeshi' => 'Bangladeshi',
        'Barbadian' => 'Barbadian',
        'Belarusian' => 'Belarusian',
        'Belgian' => 'Belgian',
        'Belizean' => 'Belizean',
        'Beninese' => 'Beninese',
        'Bermudian' => 'Bermudian',
        'Bhutanese' => 'Bhutanese',
        'Bolivian' => 'Bolivian',
        'Bosnian or Herzegovinian' => 'Bosnian or Herzegovinian',
        'Botswanan' => 'Botswanan', // Motswana (singular), Batswana (plural)
        'Brazilian' => 'Brazilian',
        'British Indian Ocean Territory' => 'British Indian Ocean Territory', // No permanent population
        'British Virgin Islander' => 'British Virgin Islander',
        'Bruneian' => 'Bruneian',
        'Bulgarian' => 'Bulgarian',
        'Burkinabe' => 'Burkinabe',
        'Burundian' => 'Burundian',
        'Cambodian' => 'Cambodian',
        'Cameroonian' => 'Cameroonian',
        'Canadian' => 'Canadian',
        'Cape Verdean' => 'Cape Verdean',
        'Caymanian' => 'Caymanian',
        'Central African' => 'Central African',
        'Chadian' => 'Chadian',
        'Chilean' => 'Chilean',
        'Chinese' => 'Chinese',
        'Christmas Islander' => 'Christmas Islander',
        'Cocos Islander' => 'Cocos Islander',
        'Colombian' => 'Colombian',
        'Comoran' => 'Comoran',
        'Cook Islander' => 'Cook Islander',
        'Costa Rican' => 'Costa Rican',
        'Croatian' => 'Croatian',
        'Cuban' => 'Cuban',
        'Curacaoan' => 'Curacaoan',
        'Cypriot' => 'Cypriot',
        'Czech' => 'Czech',
        'Congolese (Democratic Republic)' => 'Congolese (Democratic Republic)',
        'Danish' => 'Danish',
        'Djiboutian' => 'Djiboutian',
        'Dominican (Dominica)' => 'Dominican (Dominica)', // Note: Different from Dominican Republic
        'Dominican (Dominican Republic)' => 'Dominican (Dominican Republic)',
        'East Timorese' => 'East Timorese',
        'Ecuadorian' => 'Ecuadorian',
        'Egyptian' => 'Egyptian',
        'Salvadoran' => 'Salvadoran',
        'Equatorial Guinean' => 'Equatorial Guinean',
        'Eritrean' => 'Eritrean',
        'Estonian' => 'Estonian',
        'Eswatini' => 'Eswatini', // Swazi
        'Ethiopian' => 'Ethiopian',
        'Falkland Islander' => 'Falkland Islander',
        'Faroese' => 'Faroese',
        'Fijian' => 'Fijian',
        'Finnish' => 'Finnish',
        'French' => 'French',
        'French Polynesian' => 'French Polynesian',
        'Gabonese' => 'Gabonese',
        'Gambian' => 'Gambian',
        'Georgian' => 'Georgian',
        'German' => 'German',
        'Ghanaian' => 'Ghanaian',
        'Gibraltarian' => 'Gibraltarian',
        'Greek' => 'Greek',
        'Greenlandic' => 'Greenlandic',
        'Grenadian' => 'Grenadian',
        'Guamanian' => 'Guamanian',
        'Guatemalan' => 'Guatemalan',
        'Guernsian' => 'Guernsian', // From Guernsey
        'Guinean' => 'Guinean',
        'Guinea-Bissau national' => 'Guinea-Bissau national', // Bissau-Guinean
        'Guyanese' => 'Guyanese',
        'Haitian' => 'Haitian',
        'Honduran' => 'Honduran',
        'Hong Konger' => 'Hong Konger',
        'Hungarian' => 'Hungarian',
        'Icelandic' => 'Icelandic',
        'Indian' => 'Indian',
        'Indonesian' => 'Indonesian',
        'Iranian' => 'Iranian',
        'Iraqi' => 'Iraqi',
        'Irish' => 'Irish',
        'Manx' => 'Manx', // From Isle of Man
        'Italian' => 'Italian',
        'Ivorian' => 'Ivorian',
        'Jamaican' => 'Jamaican',
        'Japanese' => 'Japanese',
        'Jerseyman or Jerseywoman' => 'Jerseyman or Jerseywoman', // From Jersey
        'Jordanian' => 'Jordanian',
        'Kazakhstani' => 'Kazakhstani',
        'Kenyan' => 'Kenyan',
        'I-Kiribati' => 'I-Kiribati',
        'Kosovan' => 'Kosovan',
        'Kuwaiti' => 'Kuwaiti',
        'Kyrgyz' => 'Kyrgyz',
        'Lao' => 'Lao', // or Laotian
        'Latvian' => 'Latvian',
        'Lebanese' => 'Lebanese',
        'Mosotho' => 'Mosotho', // Basotho (plural)
        'Liberian' => 'Liberian',
        'Libyan' => 'Libyan',
        'Liechtensteiner' => 'Liechtensteiner',
        'Lithuanian' => 'Lithuanian',
        'Luxembourger' => 'Luxembourger',
        'Macanese' => 'Macanese',
        'Malagasy' => 'Malagasy',
        'Malawian' => 'Malawian',
        'Malaysian' => 'Malaysian',
        'Maldivian' => 'Maldivian',
        'Malian' => 'Malian',
        'Maltese' => 'Maltese',
        'Marshallese' => 'Marshallese',
        'Mauritanian' => 'Mauritanian',
        'Mauritian' => 'Mauritian',
        'Mahoran' => 'Mahoran', // From Mayotte
        'Mexican' => 'Mexican',
        'Micronesian' => 'Micronesian',
        'Moldovan' => 'Moldovan',
        'Monacan or Monégasque' => 'Monacan or Monégasque',
        'Mongolian' => 'Mongolian',
        'Montenegrin' => 'Montenegrin',
        'Montserratian' => 'Montserratian',
        'Moroccan' => 'Moroccan',
        'Mozambican' => 'Mozambican',
        'Burmese' => 'Burmese', // Myanma
        'Namibian' => 'Namibian',
        'Nauruan' => 'Nauruan',
        'Nepalese' => 'Nepalese',
        'Dutch' => 'Dutch',
        'Netherlands Antillean' => 'Netherlands Antillean',
        'New Caledonian' => 'New Caledonian',
        'New Zealander' => 'New Zealander', // Kiwi
        'Nicaraguan' => 'Nicaraguan',
        'Nigerien' => 'Nigerien',
        'Nigerian' => 'Nigerian',
        'Niuean' => 'Niuean',
        'North Korean' => 'North Korean',
        'North Macedonian' => 'North Macedonian',
        'Northern Mariana Islander' => 'Northern Mariana Islander',
        'Norwegian' => 'Norwegian',
        'Omani' => 'Omani',
        'Pakistani' => 'Pakistani',
        'Palauan' => 'Palauan',
        'Palestinian' => 'Palestinian',
        'Panamanian' => 'Panamanian',
        'Papua New Guinean' => 'Papua New Guinean',
        'Paraguayan' => 'Paraguayan',
        'Peruvian' => 'Peruvian',
        'Filipino' => 'Filipino',
        'Pitcairn Islander' => 'Pitcairn Islander',
        'Polish' => 'Polish',
        'Portuguese' => 'Portuguese',
        'Puerto Rican' => 'Puerto Rican',
        'Qatari' => 'Qatari',
        'Congolese (Republic)' => 'Congolese (Republic)',
        'Reunionese' => 'Reunionese', // Réunionnais
        'Romanian' => 'Romanian',
        'Russian' => 'Russian',
        'Rwandan' => 'Rwandan',
        'Saint Barthélemy Islander' => 'Saint Barthélemy Islander',
        'Saint Helenian' => 'Saint Helenian',
        'Kittitian or Nevisian' => 'Kittitian or Nevisian',
        'Saint Lucian' => 'Saint Lucian',
        'Saint Martiner' => 'Saint Martiner', // For both French and Dutch sides usually
        'Saint Pierre and Miquelon national' => 'Saint Pierre and Miquelon national',
        'Vincentian' => 'Vincentian',
        'Samoan' => 'Samoan',
        'Sammarinese' => 'Sammarinese',
        'Sao Tomean' => 'Sao Tomean',
        'Saudi Arabian' => 'Saudi Arabian',
        'Senegalese' => 'Senegalese',
        'Serbian' => 'Serbian',
        'Seychellois' => 'Seychellois',
        'Sierra Leonean' => 'Sierra Leonean',
        'Singaporean' => 'Singaporean',
        'Sint Maartener' => 'Sint Maartener',
        'Slovak' => 'Slovak',
        'Slovenian' => 'Slovenian',
        'Solomon Islander' => 'Solomon Islander',
        'Somali' => 'Somali',
        'South African' => 'South African',
        'South Korean' => 'South Korean',
        'South Sudanese' => 'South Sudanese',
        'Spanish' => 'Spanish',
        'Sri Lankan' => 'Sri Lankan',
        'Sudanese' => 'Sudanese',
        'Surinamese' => 'Surinamese',
        'Svalbard and Jan Mayen' => 'Svalbard and Jan Mayen', // No permanent demonym
        'Swedish' => 'Swedish',
        'Swiss' => 'Swiss',
        'Syrian' => 'Syrian',
        'Taiwanese' => 'Taiwanese',
        'Tajik' => 'Tajik',
        'Tanzanian' => 'Tanzanian',
        'Thai' => 'Thai',
        'Togolese' => 'Togolese',
        'Tokelauan' => 'Tokelauan',
        'Tongan' => 'Tongan',
        'Trinidadian or Tobagonian' => 'Trinidadian or Tobagonian',
        'Tunisian' => 'Tunisian',
        'Turkish' => 'Turkish',
        'Turkmen' => 'Turkmen',
        'Turks and Caicos Islander' => 'Turks and Caicos Islander',
        'Tuvaluan' => 'Tuvaluan',
        'U.S. Virgin Islander' => 'U.S. Virgin Islander',
        'Ugandan' => 'Ugandan',
        'Ukrainian' => 'Ukrainian',
        'Emirati' => 'Emirati',
        'British' => 'British', // or English, Scottish, Welsh, Northern Irish
        'American' => 'American',
        'Uruguayan' => 'Uruguayan',
        'Uzbekistani' => 'Uzbekistani', // or Uzbek
        'Vanuatuan' => 'Vanuatuan', // Ni-Vanuatu
        'Vatican citizen' => 'Vatican citizen',
        'Venezuelan' => 'Venezuelan',
        'Vietnamese' => 'Vietnamese',
        'Wallisian or Futunan' => 'Wallisian or Futunan',
        'Sahrawi' => 'Sahrawi',
        'Yemeni' => 'Yemeni',
        'Zambian' => 'Zambian',
        'Zimbabwean' => 'Zimbabwean',
    ],

    /*
    |--------------------------------------------------------------------------
    | Countries to Languages Mapping
    |--------------------------------------------------------------------------
    |
    | This file maps countries to their primary languages and direction
    | Used for email localization when sending to customers
    |
    */

    'languages' => [
        // Arabic speaking countries
        'AF' => 'fa', // Afghanistan
        'DZ' => 'ar', // Algeria
        'BH' => 'ar', // Bahrain
        'EG' => 'ar', // Egypt
        'IQ' => 'ar', // Iraq
        'JO' => 'ar', // Jordan
        'KW' => 'ar', // Kuwait
        'LB' => 'ar', // Lebanon
        'LY' => 'ar', // Libya
        'MR' => 'ar', // Mauritania
        'MA' => 'ar', // Morocco
        'OM' => 'ar', // Oman
        'PS' => 'ar', // Palestine
        'QA' => 'ar', // Qatar
        'SA' => 'ar', // Saudi Arabia
        'SD' => 'ar', // Sudan
        'SY' => 'ar', // Syria
        'TN' => 'ar', // Tunisia
        'AE' => 'ar', // United Arab Emirates
        'YE' => 'ar', // Yemen

        // English speaking countries
        'AU' => 'en', // Australia
        'CA' => 'en', // Canada
        'IE' => 'en', // Ireland
        'NZ' => 'en', // New Zealand
        'GB' => 'en', // United Kingdom
        'US' => 'en', // United States

        // European languages
        'AT' => 'de', // Austria
        'BE' => 'fr', // Belgium (Also Dutch, but using French as primary)
        'BG' => 'bg', // Bulgaria
        'HR' => 'hr', // Croatia
        'CZ' => 'cs', // Czech Republic
        'DK' => 'da', // Denmark
        'EE' => 'et', // Estonia
        'FI' => 'fi', // Finland
        'FR' => 'fr', // France
        'DE' => 'de', // Germany
        'GR' => 'el', // Greece
        'HU' => 'hu', // Hungary
        'IS' => 'is', // Iceland
        'IT' => 'it', // Italy
        'LV' => 'lv', // Latvia
        'LT' => 'lt', // Lithuania
        'LU' => 'fr', // Luxembourg
        'MT' => 'mt', // Malta
        'NL' => 'nl', // Netherlands
        'NO' => 'no', // Norway
        'PL' => 'pl', // Poland
        'PT' => 'pt', // Portugal
        'RO' => 'ro', // Romania
        'SK' => 'sk', // Slovakia
        'SI' => 'sl', // Slovenia
        'ES' => 'es', // Spain
        'SE' => 'sv', // Sweden
        'CH' => 'de', // Switzerland (Also French and Italian, but using German as primary)

        // Asian languages
        'CN' => 'zh', // China
        'HK' => 'zh', // Hong Kong
        'JP' => 'ja', // Japan
        'KR' => 'ko', // South Korea
        'TW' => 'zh', // Taiwan
        'TH' => 'th', // Thailand
        'VN' => 'vi', // Vietnam
        'IN' => 'hi', // India
        'ID' => 'id', // Indonesia
        'MY' => 'ms', // Malaysia
        'PH' => 'fil', // Philippines
        'SG' => 'en', // Singapore

        // Other major languages
        'BR' => 'pt', // Brazil
        'MX' => 'es', // Mexico
        'AR' => 'es', // Argentina
        'CL' => 'es', // Chile
        'CO' => 'es', // Colombia
        'PE' => 'es', // Peru
        'VE' => 'es', // Venezuela
        'RU' => 'ru', // Russia
        'TR' => 'tr', // Turkey
        'IR' => 'fa', // Iran
        'IL' => 'he', // Israel
        'PK' => 'ur', // Pakistan
    ],

    /*
    |--------------------------------------------------------------------------
    | RTL Languages
    |--------------------------------------------------------------------------
    |
    | List of languages that use right-to-left text direction
    |
    */
    'rtl_languages' => [
        'ar', // Arabic
        'fa', // Persian
        'he', // Hebrew
        'ur', // Urdu
    ],
];
